### ISSUE TITLE
Vector images

### ISSUE THREAD

**Issue by samcarter** [BenSt099/isosafety#1]
Do you have any plans to add vector versions of the images? 

It seems that the icons are available as .svg from wikipedia, e.g. https://upload.wikimedia.org/wikipedia/commons/5/57/ISO_7010_E001.svg , which could be converted to .pdf. This would make their inclusion into documents faster and give better quality results.

**Comment by jasperhabicht** [comment]
If the vecorized versions are not exactly those from the standard, which could be an argument to stick to PNG, but I did not look into the relevant standard, it would still be good to provide vecorized variants in the package and make these available via an package option, for example.

**Comment by BenSt099** [comment]
I haven't thought about it yet, but of course! I will try to include them in the next version (approximately 1 month, possibly even around Christmas, as I am currently very busy). However, I need to check if I have the permission to use files from Wikipedia

**Comment by samcarter** [comment]
> However, I need to check if I have the permission to use these files from Wikipedia

I did not check all icons, but https://en.wikipedia.org/wiki/File:ISO_7010_E001.svg is in the public domain, so it should be safe to use (disclaimer: I'm not a lawyer)

**Comment by BenSt099** [comment]
yea, i found the same information (https://en.wikipedia.org/wiki/Wikipedia:Public_domain), thank you

**Comment by BenSt099** [comment]
Version 1.1 is now available on CTAN; it uses the pdf version of those signs; png-format was removed, but the commands stayed the same and i updated the documentation
