### ISSUE TITLE
ISO_7010_E003.pdf is wrong

### ISSUE THREAD

**Issue by SwitWu** [BenSt099/isosafety#3]
As the title says, the file `ISO_7010_E003.pdf` in the `isosafety-pdfs` directory is wrong.

**Comment by BenSt099** [comment]
I tried it on my machine and were able to reproduce this issue. Seems like the file is corrupt or broken. I will fix this. For a quick fix, go under `texlive/2024/tex/latex/isosafety/isosafety-pdfs` and replace the file with the one in this repository (the one in the folder `isosafety/tex/isosafety-pdfs`)

**Comment by BenSt099** [comment]
Seems like mutliple files have this issue (e.g. W012)

**Comment by BenSt099** [comment]
I uploaded a newer version of this package to CTAN. If this issue persists, please report again. Thanks for reporting this issue!
