### ISSUE TITLE
Improvement of the package code

### ISSUE THREAD

**Issue by SwitWu** [BenSt099/isosafety#4]
The definition
```tex
\newcommand{\Isosign}[1]{\isosafetypath /isosafety-pdfs/ISO_7010_#1.pdf}
```
is unnecessarily complex. In fact we can just define it as
```tex
\newcommand{\Isosign}[1]{ISO_7010_#1.pdf}
```
since these PDF files are located in the texmf tree (under `texmf-dist/tex/latex`) and they can be found by TeX by file name.

Therefore the mandatory package option `fullpath` also seems unnecessary.

**Comment by BenSt099** [comment]
This mandatory option was adapted in version 1.2 because of an issue in v1.1. I will try and see if your suggestion works

**Comment by BenSt099** [comment]
Seems like this suggestion does not work. On my system (Win11), latex is not able to find the pdfs (thats the issue I had in v1.1). Did you try your suggestion on your system?

**Comment by SwitWu** [comment]
On my machine (macOS), the code:
```tex
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{ISO_7010_F001.pdf}
\end{document}
```
works. And running `kpsewhich ISO_7010_F001.pdf` in the terminal gives its absolute path successfully.

**Comment by BenSt099** [comment]
running `kpsewhich ISO_7010_F001.pdf` on my system does not return anything (although running `kpsewhich isosafety.sty` gives me the correct location). Maybe it's a Windows problem. I will do some research on this and if I don't find any other solution, I will make the fullpath an optional parameter like you suggested

**Comment by SwitWu** [comment]
Today I test the command on my another machine (Windows 10), it also works fine.

![QQ20240830-121928](https://github.com/user-attachments/assets/8f35a782-2287-4de0-ab76-cb1be7d3a535)

**Comment by BenSt099** [comment]
Thanks for testing it. I will make the `fullpath`-option optional in the next version

**Comment by BenSt099** [comment]
Next version is on its way to CTAN. Thanks for suggesting this enhancement! If you have other enhancements / issues, feel free to open another issue ;-).
